### ISSUE TITLE
Program ND (basic)

### ISSUE THREAD

**Issue by jamlen** [x-bureau/Airbus-A318#4]
Implement basic Navigation Display

# Acceptance Criteria:

- [x] Displays G/S
- [x] Displays TAS
- [x] Displays current winds with indicator
- [x] Implement VOR mode page
  - [x] Displays VOR freq, course, ident
  - [x] Displays 360º compass rose
  - [x] Displays VOR course pointer
  - [x] Displays lateral deviation bar

**Comment by OldGroof** [comment]
All VOR stuff has been completed for a while.
