### ISSUE TITLE
Misalignment in Default livery

### ISSUE THREAD

**Issue by therectifier** [x-bureau/Airbus-A318#63]
![image](https://user-images.githubusercontent.com/96103963/221479302-7becb6e7-3ef0-46b7-98b2-f7c5b9bb2395.png)

Stripe on left and right sides are misaligned

**Comment by PilotLisa** [comment]
@Martian-Taiwan. Fix the livery please.

**Comment by Martian-Taiwan** [comment]
I will delete this livery but re-upload it when it is ready to fly again.
